<a href="https://colab.research.google.com/github/Charan832844/EDA-project-1/blob/main/25BAI0088.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Auto_EDA dataset.csv')

In [3]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [4]:
df.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
387,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
388,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
389,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
390,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
391,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [6]:
df.sample(5)

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
59,20.0,4,140.0,90,2408,19.5,72,1,chevrolet vega
227,16.0,8,400.0,180,4220,11.1,77,1,pontiac grand prix lj
225,19.0,6,225.0,100,3630,17.7,77,1,plymouth volare custom
172,18.0,6,171.0,97,2984,14.5,75,1,ford pinto
259,18.1,6,258.0,120,3410,15.1,78,1,amc concord d/l

In [7]:
df.shape

(392, 9)

In [8]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin', 'name'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 392 entries, 0 to 391
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    int64
 4   weight        392 non-null    int64
 5   acceleration  392 non-null    float64
 6   year          392 non-null    int64
 7   origin        392 non-null    int64
 8   name          392 non-null    object
dtypes: float64(3), int64(5), object(1)
memory usage: 27.7+ KB

In [10]:
df.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin
count,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000
mean,23.445918,5.471939,194.411990,104.469388,2977.584184,15.541327,75.979592,1.576531
std,7.805007,1.705783,104.644004,38.491160,849.402560,2.758864,3.683737,0.805518
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.000000,4.000000,105.000000,75.000000,2225.250000,13.775000,73.000000,1.000000
50%,22.750000,4.000000,151.000000,93.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,275.750000,126.000000,3614.750000,17.025000,79.000000,2.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,3.000000

In [11]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower        int64
weight            int64
acceleration    float64
year              int64
origin            int64
name             object
dtype: object

In [12]:
df['weight'].dtype

dtype('int64')

In [13]:
df.max()

mpg                         46.6
cylinders                      8
displacement               455.0
horsepower                   230
weight                      5140
acceleration                24.8
year                          82
origin                         3
name            vw rabbit custom
dtype: object

In [14]:
df.min()

mpg                                 9.0
cylinders                             3
displacement                       68.0
horsepower                           46
weight                             1613
acceleration                        8.0
year                                 70
origin                                1
name            amc ambassador brougham
dtype: object

In [23]:
df['weight'].mean()

np.float64(2977.5841836734694)

In [22]:
df['weight'].median()

2803.5

In [24]:
df['weight'].std()

849.4025600429494